# CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso pipeline
name: 'Execução por Deploy'


#regras de disparo (ou gatilhos ou triggers)
#gatilho de execução manual = workflow_dispatch
#gatilho de execução a partir de outro pipe = workflow_run

on: 
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# trabalhos/tarefas dentro do pipeline = jobs
jobs:   
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

#passos do script de build
    steps:
    #clone do projeto
      - uses: actions/checkout@v4

    #instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
        

    #instalacao do Yarn
      - name: Insatalando Yarn
        run: npm instal -g yarn

   #instalação das dependências
      - name: Instalando dependências
        run: yarn

   #instalação do Playwrigth
      - name: Instalando Playwright
        run: yarn playwright install

   #executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e