# CI de Nível 04 - Disparo dos testes dentro do pipe de dev


name: 'Execução Integrada'

on: 
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm instal -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Checando padronização do código
        run: yarn lint

  unidade: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm instal -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes de unidade
        run: yarn test

  e2e-tests: 
    runs-on: ubuntu-latest

    steps:
    #clone do projeto
      - uses: actions/checkout@v4

    #instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
        

    #instalacao do Yarn
      - name: Insatalando Yarn
        run: npm instal -g yarn

   #instalação das dependências
      - name: Instalando dependências
        run: yarn

   #instalação do Playwrigth
      - name: Instalando Playwright
        run: yarn playwright install

   #executar os testes e2e
      - name: Executando Testes e2e
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        #se o pipeline ate esse ponto nao for cancelado ate esse ponto, executa os passos abaixo
        if: ${{ !cancelled() }}
        with: 
          name: relatorio
          path: ./playwright-report   

  deploy: 
    runs-on: ubuntu-latest

    stpes: 
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"